### ISSUE TITLE
InitPickandPlace.c" because it was not found		

### ISSUE THREAD

**Issue by darkworks** [briandorey/pickandplacesoftware#1]
am trying to build the build project but getting error 

Severity	Code	Description	Project	File	Line	Suppression State
`Error		Could not copy the file Projects\PickAndPlace\PNPControllerKFlop\InitPickandPlace.c" because it was not found.	PNPControllerKFlop	`		

can you share the missing file  please 

thanks

**Comment by briandorey** [comment]
I am sorry for the late reply, I didnt get a notification of the message on Github
[InitPickandPlace.txt](https://github.com/briandorey/pickandplacesoftware/files/3815550/InitPickandPlace.txt)

**Comment by darkworks** [comment]
thanks :)
